version: 2

updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily

- package-ecosystem: docker
  directory: "/src/sql-server/rebuild-indexes"
  schedule:
    interval: daily
